METRE_LENGTH = 64 -- how many pixels represent 1 metre

VIRTUAL_WIDTH = 1280
VIRTUAL_HEIGHT = 720

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

LARGE_FONT_SIZE = 256

POINT_HITBOX = 40

POINT_IN_LINE_SEGMENT_TOLERANCE_VALUE = 0.01

PIXEL_AREA_SCALE_FACTOR = 1/100

PENTAGON_POINTS = 10
TRIANGLE_POINTS = -2
QUAD_POINTS = -3
HEXAGON_POINTS = -5
HEPTAGON_POINTS = -6
